---
- name: cleanup
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - include: "{{ lookup('env','ANSIBLE_COMMON_DIR') }}/tasks/set-facts.yml"
    - name: re_tag_built_docker_images
      docker_image:
        force_tag: true
        name: talsenteam/docker-nginx-certbot:v1.17.4
        repository: talsenteam/docker-nginx-certbot:v1.17.4-cache
        source: local
      ignore_errors: true
    - name: un_tag_built_docker_images
      docker_image:
        name: talsenteam/docker-nginx-certbot
        state: absent
        tag: v1.17.4
      ignore_errors: true
    - include: "{{ lookup('env','ANSIBLE_COMMON_DIR') }}/tasks/remove-test-directory.yml"
  vars:
    ansible_python_interpreter: /usr/bin/python3
