---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      connection: local
lint:
  name: yamllint
platforms:
  - name: delegated_localhost
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      delegated_localhost:
        ansible_connection: local
scenario:
  name: default
  test_sequence:
    - lint
    - syntax
    - cleanup
    - converge
    - idempotence
    - verify
    - cleanup
verifier:
  name: testinfra
  lint:
    name: flake8
