---
- name: copy_required_files
  copy:
    dest: "{{ test_dir }}/{{ item.name }}"
    mode: 0o600
    remote_src: true
    src: "{{ project_dir }}/{{ item.name }}"
  with_items:
    - name: bash/docker/compose/up.bash
    - name: bash/docker/image/build.bash
    - name: bash/util/functions.bash
    - name: docker/{{ configuration }}/default.docker
    - name: docker/{{ configuration }}/default.docker-compose
    - name: env/{{ configuration }}/docker-containers.env
    - name: env/{{ configuration }}/docker-images.env
  notify: execute_command
