---
- name: set_facts
  set_fact:
    project_dir: "{{ lookup('env','PROJECT_DIR') }}"
    tests_dir: "{{ lookup('env','TESTS_DIR') }}"
    test_dir: "{{ lookup('env','TESTS_DIR') }}/{{ lookup('env','ROLE_NAME') }}"
