---
- name: cleanup
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - include: "{{ lookup('env','ANSIBLE_COMMON_DIR') }}/tasks/set-facts.yml"
    - name: remove_running_docker_container
      docker_container:
        name: server--nginx-certbot
        state: absent
    - name: remove_test_directory
      file:
        path: "{{ test_dir }}"
        state: absent
  vars:
    ansible_python_interpreter: /usr/bin/python3
